export const STORAGE_KEY = 'GRE READING'

// passage
export const PASSAGE_SET = 'PASSAGE_SET '
export const PASSAGE_ACTIVE = 'PASSAGE_ACTIVE'

export const ACTION_PASSAGE_FETCH = 'ACTION_PASSAGE_FETCH'

// config

export const CONFIG_TITLE_VISIBLE = 'CONFIG_TITLE_VISIBLE'
export const CONFIG_FONTSIZE = 'CONFIG_FONTSIZE'
